name: Code Review

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run cppcheck
        run: tools/run-cppcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JOB_ID: ${{ github.job }}

  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format
        run: tools/run-clang-format && git diff --exit-code

  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run clang-tidy
        run: tools/run-clang-tidy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JOB_ID: ${{ github.job }}
